name: testbot1

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test
      
      - name: Build & Push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          APP: "testbot1"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          make DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME}" DOCKERHUB_TOKEN="${DOCKERHUB_TOKEN}" image push
